-- 仅在组织 migration 已完成后运行；正常迁移已通过 DEFAULT 回填。
-- 幂等修复空归属，不覆盖任何已有组织；先停写并备份。
BEGIN;
INSERT INTO organizations (id,name) VALUES ('default-organization','默认组织') ON CONFLICT (id) DO NOTHING;
UPDATE "users" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "lab_datasets" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "lab_agent_versions" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "lab_runs" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "lab_recorded_imports" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "lab_failures" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "lab_experiments" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "lab_experiment_runs" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "lab_release_decisions" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "lab_operation_logs" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "workspaces" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "workspace_members" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "agents" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "agent_versions" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "runs" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "trace_events" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "decision_records" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "fact_assertions" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "decision_evidence" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "applications" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "application_runs" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "tool_approvals" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "evaluation_datasets" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "evaluation_dataset_cases" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "evaluators" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "agent_evaluation_runs" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "evaluation_results" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "interviews" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "session_costs" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "usage_ledger" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "messages" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "reports" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "user_tool_preferences" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "interview_tasks" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "answer_histories" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "target_jobs" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "job_skill_requirements" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "interview_questions" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "interview_answers" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "evaluation_runs" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "assessment_evidence" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "candidate_skill_states" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "training_recommendations" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "training_attempts" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
UPDATE "reflection_logs" SET "organizationId" = 'default-organization' WHERE "organizationId" IS NULL;
COMMIT;
