-- 加性迁移；存量统一归入默认组织，停写窗口内执行。
BEGIN;
CREATE TABLE "organizations" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO "organizations" ("id", "name") VALUES ('default-organization', '默认组织');
ALTER TABLE "users" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "users_organizationId_idx" ON "users" ("organizationId");
CREATE UNIQUE INDEX "users_id_organizationId_key" ON "users" ("id", "organizationId");
ALTER TABLE "users" ADD CONSTRAINT "users_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "lab_datasets" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "lab_datasets_organizationId_idx" ON "lab_datasets" ("organizationId");
CREATE UNIQUE INDEX "lab_datasets_id_organizationId_key" ON "lab_datasets" ("id", "organizationId");
ALTER TABLE "lab_datasets" ADD CONSTRAINT "lab_datasets_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "lab_agent_versions" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "lab_agent_versions_organizationId_idx" ON "lab_agent_versions" ("organizationId");
CREATE UNIQUE INDEX "lab_agent_versions_id_organizationId_key" ON "lab_agent_versions" ("id", "organizationId");
ALTER TABLE "lab_agent_versions" ADD CONSTRAINT "lab_agent_versions_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "lab_runs" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "lab_runs_organizationId_idx" ON "lab_runs" ("organizationId");
CREATE UNIQUE INDEX "lab_runs_id_organizationId_key" ON "lab_runs" ("id", "organizationId");
ALTER TABLE "lab_runs" ADD CONSTRAINT "lab_runs_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "lab_recorded_imports" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "lab_recorded_imports_organizationId_idx" ON "lab_recorded_imports" ("organizationId");
CREATE UNIQUE INDEX "lab_recorded_imports_id_organizationId_key" ON "lab_recorded_imports" ("id", "organizationId");
ALTER TABLE "lab_recorded_imports" ADD CONSTRAINT "lab_recorded_imports_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "lab_failures" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "lab_failures_organizationId_idx" ON "lab_failures" ("organizationId");
CREATE UNIQUE INDEX "lab_failures_id_organizationId_key" ON "lab_failures" ("id", "organizationId");
ALTER TABLE "lab_failures" ADD CONSTRAINT "lab_failures_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "lab_experiments" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "lab_experiments_organizationId_idx" ON "lab_experiments" ("organizationId");
CREATE UNIQUE INDEX "lab_experiments_id_organizationId_key" ON "lab_experiments" ("id", "organizationId");
ALTER TABLE "lab_experiments" ADD CONSTRAINT "lab_experiments_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "lab_experiment_runs" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "lab_experiment_runs_organizationId_idx" ON "lab_experiment_runs" ("organizationId");
CREATE UNIQUE INDEX "lab_experiment_runs_id_organizationId_key" ON "lab_experiment_runs" ("id", "organizationId");
ALTER TABLE "lab_experiment_runs" ADD CONSTRAINT "lab_experiment_runs_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "lab_release_decisions" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "lab_release_decisions_organizationId_idx" ON "lab_release_decisions" ("organizationId");
CREATE UNIQUE INDEX "lab_release_decisions_id_organizationId_key" ON "lab_release_decisions" ("id", "organizationId");
ALTER TABLE "lab_release_decisions" ADD CONSTRAINT "lab_release_decisions_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "lab_operation_logs" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "lab_operation_logs_organizationId_idx" ON "lab_operation_logs" ("organizationId");
CREATE UNIQUE INDEX "lab_operation_logs_id_organizationId_key" ON "lab_operation_logs" ("id", "organizationId");
ALTER TABLE "lab_operation_logs" ADD CONSTRAINT "lab_operation_logs_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "workspaces" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "workspaces_organizationId_idx" ON "workspaces" ("organizationId");
CREATE UNIQUE INDEX "workspaces_id_organizationId_key" ON "workspaces" ("id", "organizationId");
ALTER TABLE "workspaces" ADD CONSTRAINT "workspaces_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "workspace_members" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "workspace_members_organizationId_idx" ON "workspace_members" ("organizationId");
CREATE UNIQUE INDEX "workspace_members_id_organizationId_key" ON "workspace_members" ("id", "organizationId");
ALTER TABLE "workspace_members" ADD CONSTRAINT "workspace_members_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "agents" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "agents_organizationId_idx" ON "agents" ("organizationId");
CREATE UNIQUE INDEX "agents_id_organizationId_key" ON "agents" ("id", "organizationId");
ALTER TABLE "agents" ADD CONSTRAINT "agents_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "agent_versions" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "agent_versions_organizationId_idx" ON "agent_versions" ("organizationId");
CREATE UNIQUE INDEX "agent_versions_id_organizationId_key" ON "agent_versions" ("id", "organizationId");
ALTER TABLE "agent_versions" ADD CONSTRAINT "agent_versions_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "runs" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "runs_organizationId_idx" ON "runs" ("organizationId");
CREATE UNIQUE INDEX "runs_id_organizationId_key" ON "runs" ("id", "organizationId");
ALTER TABLE "runs" ADD CONSTRAINT "runs_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "trace_events" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "trace_events_organizationId_idx" ON "trace_events" ("organizationId");
CREATE UNIQUE INDEX "trace_events_id_organizationId_key" ON "trace_events" ("id", "organizationId");
ALTER TABLE "trace_events" ADD CONSTRAINT "trace_events_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "decision_records" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "decision_records_organizationId_idx" ON "decision_records" ("organizationId");
CREATE UNIQUE INDEX "decision_records_id_organizationId_key" ON "decision_records" ("id", "organizationId");
ALTER TABLE "decision_records" ADD CONSTRAINT "decision_records_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "fact_assertions" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "fact_assertions_organizationId_idx" ON "fact_assertions" ("organizationId");
CREATE UNIQUE INDEX "fact_assertions_id_organizationId_key" ON "fact_assertions" ("id", "organizationId");
ALTER TABLE "fact_assertions" ADD CONSTRAINT "fact_assertions_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "decision_evidence" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "decision_evidence_organizationId_idx" ON "decision_evidence" ("organizationId");
CREATE UNIQUE INDEX "decision_evidence_id_organizationId_key" ON "decision_evidence" ("id", "organizationId");
ALTER TABLE "decision_evidence" ADD CONSTRAINT "decision_evidence_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "applications" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "applications_organizationId_idx" ON "applications" ("organizationId");
CREATE UNIQUE INDEX "applications_id_organizationId_key" ON "applications" ("id", "organizationId");
ALTER TABLE "applications" ADD CONSTRAINT "applications_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "application_runs" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "application_runs_organizationId_idx" ON "application_runs" ("organizationId");
CREATE UNIQUE INDEX "application_runs_id_organizationId_key" ON "application_runs" ("id", "organizationId");
ALTER TABLE "application_runs" ADD CONSTRAINT "application_runs_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "tool_approvals" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "tool_approvals_organizationId_idx" ON "tool_approvals" ("organizationId");
CREATE UNIQUE INDEX "tool_approvals_id_organizationId_key" ON "tool_approvals" ("id", "organizationId");
ALTER TABLE "tool_approvals" ADD CONSTRAINT "tool_approvals_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "evaluation_datasets" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "evaluation_datasets_organizationId_idx" ON "evaluation_datasets" ("organizationId");
CREATE UNIQUE INDEX "evaluation_datasets_id_organizationId_key" ON "evaluation_datasets" ("id", "organizationId");
ALTER TABLE "evaluation_datasets" ADD CONSTRAINT "evaluation_datasets_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "evaluation_dataset_cases" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "evaluation_dataset_cases_organizationId_idx" ON "evaluation_dataset_cases" ("organizationId");
CREATE UNIQUE INDEX "evaluation_dataset_cases_id_organizationId_key" ON "evaluation_dataset_cases" ("id", "organizationId");
ALTER TABLE "evaluation_dataset_cases" ADD CONSTRAINT "evaluation_dataset_cases_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "evaluators" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "evaluators_organizationId_idx" ON "evaluators" ("organizationId");
CREATE UNIQUE INDEX "evaluators_id_organizationId_key" ON "evaluators" ("id", "organizationId");
ALTER TABLE "evaluators" ADD CONSTRAINT "evaluators_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "agent_evaluation_runs" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "agent_evaluation_runs_organizationId_idx" ON "agent_evaluation_runs" ("organizationId");
CREATE UNIQUE INDEX "agent_evaluation_runs_id_organizationId_key" ON "agent_evaluation_runs" ("id", "organizationId");
ALTER TABLE "agent_evaluation_runs" ADD CONSTRAINT "agent_evaluation_runs_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "evaluation_results" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "evaluation_results_organizationId_idx" ON "evaluation_results" ("organizationId");
CREATE UNIQUE INDEX "evaluation_results_id_organizationId_key" ON "evaluation_results" ("id", "organizationId");
ALTER TABLE "evaluation_results" ADD CONSTRAINT "evaluation_results_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "interviews" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "interviews_organizationId_idx" ON "interviews" ("organizationId");
CREATE UNIQUE INDEX "interviews_id_organizationId_key" ON "interviews" ("id", "organizationId");
ALTER TABLE "interviews" ADD CONSTRAINT "interviews_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "session_costs" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "session_costs_organizationId_idx" ON "session_costs" ("organizationId");
CREATE UNIQUE INDEX "session_costs_id_organizationId_key" ON "session_costs" ("id", "organizationId");
ALTER TABLE "session_costs" ADD CONSTRAINT "session_costs_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "usage_ledger" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "usage_ledger_organizationId_idx" ON "usage_ledger" ("organizationId");
CREATE UNIQUE INDEX "usage_ledger_id_organizationId_key" ON "usage_ledger" ("id", "organizationId");
ALTER TABLE "usage_ledger" ADD CONSTRAINT "usage_ledger_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "messages" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "messages_organizationId_idx" ON "messages" ("organizationId");
CREATE UNIQUE INDEX "messages_id_organizationId_key" ON "messages" ("id", "organizationId");
ALTER TABLE "messages" ADD CONSTRAINT "messages_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "reports" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "reports_organizationId_idx" ON "reports" ("organizationId");
CREATE UNIQUE INDEX "reports_id_organizationId_key" ON "reports" ("id", "organizationId");
ALTER TABLE "reports" ADD CONSTRAINT "reports_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "user_tool_preferences" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "user_tool_preferences_organizationId_idx" ON "user_tool_preferences" ("organizationId");
CREATE UNIQUE INDEX "user_tool_preferences_id_organizationId_key" ON "user_tool_preferences" ("id", "organizationId");
ALTER TABLE "user_tool_preferences" ADD CONSTRAINT "user_tool_preferences_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "interview_tasks" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "interview_tasks_organizationId_idx" ON "interview_tasks" ("organizationId");
CREATE UNIQUE INDEX "interview_tasks_id_organizationId_key" ON "interview_tasks" ("id", "organizationId");
ALTER TABLE "interview_tasks" ADD CONSTRAINT "interview_tasks_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "answer_histories" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "answer_histories_organizationId_idx" ON "answer_histories" ("organizationId");
CREATE UNIQUE INDEX "answer_histories_id_organizationId_key" ON "answer_histories" ("id", "organizationId");
ALTER TABLE "answer_histories" ADD CONSTRAINT "answer_histories_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "target_jobs" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "target_jobs_organizationId_idx" ON "target_jobs" ("organizationId");
CREATE UNIQUE INDEX "target_jobs_id_organizationId_key" ON "target_jobs" ("id", "organizationId");
ALTER TABLE "target_jobs" ADD CONSTRAINT "target_jobs_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "job_skill_requirements" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "job_skill_requirements_organizationId_idx" ON "job_skill_requirements" ("organizationId");
CREATE UNIQUE INDEX "job_skill_requirements_id_organizationId_key" ON "job_skill_requirements" ("id", "organizationId");
ALTER TABLE "job_skill_requirements" ADD CONSTRAINT "job_skill_requirements_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "interview_questions" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "interview_questions_organizationId_idx" ON "interview_questions" ("organizationId");
CREATE UNIQUE INDEX "interview_questions_id_organizationId_key" ON "interview_questions" ("id", "organizationId");
ALTER TABLE "interview_questions" ADD CONSTRAINT "interview_questions_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "interview_answers" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "interview_answers_organizationId_idx" ON "interview_answers" ("organizationId");
CREATE UNIQUE INDEX "interview_answers_id_organizationId_key" ON "interview_answers" ("id", "organizationId");
ALTER TABLE "interview_answers" ADD CONSTRAINT "interview_answers_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "evaluation_runs" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "evaluation_runs_organizationId_idx" ON "evaluation_runs" ("organizationId");
CREATE UNIQUE INDEX "evaluation_runs_id_organizationId_key" ON "evaluation_runs" ("id", "organizationId");
ALTER TABLE "evaluation_runs" ADD CONSTRAINT "evaluation_runs_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "assessment_evidence" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "assessment_evidence_organizationId_idx" ON "assessment_evidence" ("organizationId");
CREATE UNIQUE INDEX "assessment_evidence_id_organizationId_key" ON "assessment_evidence" ("id", "organizationId");
ALTER TABLE "assessment_evidence" ADD CONSTRAINT "assessment_evidence_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "candidate_skill_states" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "candidate_skill_states_organizationId_idx" ON "candidate_skill_states" ("organizationId");
CREATE UNIQUE INDEX "candidate_skill_states_id_organizationId_key" ON "candidate_skill_states" ("id", "organizationId");
ALTER TABLE "candidate_skill_states" ADD CONSTRAINT "candidate_skill_states_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "training_recommendations" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "training_recommendations_organizationId_idx" ON "training_recommendations" ("organizationId");
CREATE UNIQUE INDEX "training_recommendations_id_organizationId_key" ON "training_recommendations" ("id", "organizationId");
ALTER TABLE "training_recommendations" ADD CONSTRAINT "training_recommendations_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "training_attempts" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "training_attempts_organizationId_idx" ON "training_attempts" ("organizationId");
CREATE UNIQUE INDEX "training_attempts_id_organizationId_key" ON "training_attempts" ("id", "organizationId");
ALTER TABLE "training_attempts" ADD CONSTRAINT "training_attempts_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "reflection_logs" ADD COLUMN "organizationId" TEXT NOT NULL DEFAULT 'default-organization';
CREATE INDEX "reflection_logs_organizationId_idx" ON "reflection_logs" ("organizationId");
CREATE UNIQUE INDEX "reflection_logs_id_organizationId_key" ON "reflection_logs" ("id", "organizationId");
ALTER TABLE "reflection_logs" ADD CONSTRAINT "reflection_logs_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations" ("id") ON DELETE RESTRICT;
ALTER TABLE "lab_runs" ADD CONSTRAINT "lab_runs_agentVersionId_org_fk" FOREIGN KEY ("agentVersionId", "organizationId") REFERENCES "lab_agent_versions" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lab_runs" ADD CONSTRAINT "lab_runs_datasetId_org_fk" FOREIGN KEY ("datasetId", "organizationId") REFERENCES "lab_datasets" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lab_recorded_imports" ADD CONSTRAINT "lab_recorded_imports_runId_org_fk" FOREIGN KEY ("runId", "organizationId") REFERENCES "lab_runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lab_failures" ADD CONSTRAINT "lab_failures_runId_org_fk" FOREIGN KEY ("runId", "organizationId") REFERENCES "lab_runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lab_experiments" ADD CONSTRAINT "lab_experiments_controlVersionId_org_fk" FOREIGN KEY ("controlVersionId", "organizationId") REFERENCES "lab_agent_versions" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lab_experiments" ADD CONSTRAINT "lab_experiments_treatmentVersionId_org_fk" FOREIGN KEY ("treatmentVersionId", "organizationId") REFERENCES "lab_agent_versions" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lab_experiments" ADD CONSTRAINT "lab_experiments_datasetId_org_fk" FOREIGN KEY ("datasetId", "organizationId") REFERENCES "lab_datasets" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lab_experiment_runs" ADD CONSTRAINT "lab_experiment_runs_experimentId_org_fk" FOREIGN KEY ("experimentId", "organizationId") REFERENCES "lab_experiments" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lab_experiment_runs" ADD CONSTRAINT "lab_experiment_runs_runId_org_fk" FOREIGN KEY ("runId", "organizationId") REFERENCES "lab_runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lab_release_decisions" ADD CONSTRAINT "lab_release_decisions_agentVersionId_org_fk" FOREIGN KEY ("agentVersionId", "organizationId") REFERENCES "lab_agent_versions" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lab_release_decisions" ADD CONSTRAINT "lab_release_decisions_datasetId_org_fk" FOREIGN KEY ("datasetId", "organizationId") REFERENCES "lab_datasets" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lab_release_decisions" ADD CONSTRAINT "lab_release_decisions_runId_org_fk" FOREIGN KEY ("runId", "organizationId") REFERENCES "lab_runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lab_release_decisions" ADD CONSTRAINT "lab_release_decisions_experimentId_org_fk" FOREIGN KEY ("experimentId", "organizationId") REFERENCES "lab_experiments" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "workspaces" ADD CONSTRAINT "workspaces_ownerId_org_fk" FOREIGN KEY ("ownerId", "organizationId") REFERENCES "users" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "workspace_members" ADD CONSTRAINT "workspace_members_workspaceId_org_fk" FOREIGN KEY ("workspaceId", "organizationId") REFERENCES "workspaces" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "workspace_members" ADD CONSTRAINT "workspace_members_userId_org_fk" FOREIGN KEY ("userId", "organizationId") REFERENCES "users" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "agents" ADD CONSTRAINT "agents_workspaceId_org_fk" FOREIGN KEY ("workspaceId", "organizationId") REFERENCES "workspaces" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "agents" ADD CONSTRAINT "agents_currentVersionId_org_fk" FOREIGN KEY ("currentVersionId", "organizationId") REFERENCES "agent_versions" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "agent_versions" ADD CONSTRAINT "agent_versions_agentId_org_fk" FOREIGN KEY ("agentId", "organizationId") REFERENCES "agents" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "runs" ADD CONSTRAINT "runs_workspaceId_org_fk" FOREIGN KEY ("workspaceId", "organizationId") REFERENCES "workspaces" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "runs" ADD CONSTRAINT "runs_agentId_org_fk" FOREIGN KEY ("agentId", "organizationId") REFERENCES "agents" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "runs" ADD CONSTRAINT "runs_agentVersionId_org_fk" FOREIGN KEY ("agentVersionId", "organizationId") REFERENCES "agent_versions" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "runs" ADD CONSTRAINT "runs_parentRunId_org_fk" FOREIGN KEY ("parentRunId", "organizationId") REFERENCES "runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "trace_events" ADD CONSTRAINT "trace_events_runId_org_fk" FOREIGN KEY ("runId", "organizationId") REFERENCES "runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "decision_records" ADD CONSTRAINT "decision_records_interviewId_org_fk" FOREIGN KEY ("interviewId", "organizationId") REFERENCES "interviews" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "decision_records" ADD CONSTRAINT "decision_records_agentId_org_fk" FOREIGN KEY ("agentId", "organizationId") REFERENCES "agents" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "decision_records" ADD CONSTRAINT "decision_records_agentVersionId_org_fk" FOREIGN KEY ("agentVersionId", "organizationId") REFERENCES "agent_versions" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "fact_assertions" ADD CONSTRAINT "fact_assertions_decisionId_org_fk" FOREIGN KEY ("decisionId", "organizationId") REFERENCES "decision_records" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "decision_evidence" ADD CONSTRAINT "decision_evidence_decisionId_org_fk" FOREIGN KEY ("decisionId", "organizationId") REFERENCES "decision_records" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "applications" ADD CONSTRAINT "applications_workspaceId_org_fk" FOREIGN KEY ("workspaceId", "organizationId") REFERENCES "workspaces" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "applications" ADD CONSTRAINT "applications_agentId_org_fk" FOREIGN KEY ("agentId", "organizationId") REFERENCES "agents" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "application_runs" ADD CONSTRAINT "application_runs_applicationId_org_fk" FOREIGN KEY ("applicationId", "organizationId") REFERENCES "applications" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "application_runs" ADD CONSTRAINT "application_runs_runId_org_fk" FOREIGN KEY ("runId", "organizationId") REFERENCES "runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "tool_approvals" ADD CONSTRAINT "tool_approvals_runId_org_fk" FOREIGN KEY ("runId", "organizationId") REFERENCES "runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "evaluation_datasets" ADD CONSTRAINT "evaluation_datasets_workspaceId_org_fk" FOREIGN KEY ("workspaceId", "organizationId") REFERENCES "workspaces" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "evaluation_dataset_cases" ADD CONSTRAINT "evaluation_dataset_cases_datasetId_org_fk" FOREIGN KEY ("datasetId", "organizationId") REFERENCES "evaluation_datasets" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "evaluators" ADD CONSTRAINT "evaluators_workspaceId_org_fk" FOREIGN KEY ("workspaceId", "organizationId") REFERENCES "workspaces" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "agent_evaluation_runs" ADD CONSTRAINT "agent_evaluation_runs_workspaceId_org_fk" FOREIGN KEY ("workspaceId", "organizationId") REFERENCES "workspaces" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "agent_evaluation_runs" ADD CONSTRAINT "agent_evaluation_runs_agentId_org_fk" FOREIGN KEY ("agentId", "organizationId") REFERENCES "agents" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "agent_evaluation_runs" ADD CONSTRAINT "agent_evaluation_runs_agentVersionId_org_fk" FOREIGN KEY ("agentVersionId", "organizationId") REFERENCES "agent_versions" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "agent_evaluation_runs" ADD CONSTRAINT "agent_evaluation_runs_datasetId_org_fk" FOREIGN KEY ("datasetId", "organizationId") REFERENCES "evaluation_datasets" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "agent_evaluation_runs" ADD CONSTRAINT "agent_evaluation_runs_evaluatorId_org_fk" FOREIGN KEY ("evaluatorId", "organizationId") REFERENCES "evaluators" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "evaluation_results" ADD CONSTRAINT "evaluation_results_evaluationRunId_org_fk" FOREIGN KEY ("evaluationRunId", "organizationId") REFERENCES "agent_evaluation_runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "evaluation_results" ADD CONSTRAINT "evaluation_results_datasetCaseId_org_fk" FOREIGN KEY ("datasetCaseId", "organizationId") REFERENCES "evaluation_dataset_cases" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "evaluation_results" ADD CONSTRAINT "evaluation_results_runId_org_fk" FOREIGN KEY ("runId", "organizationId") REFERENCES "runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "interviews" ADD CONSTRAINT "interviews_userId_org_fk" FOREIGN KEY ("userId", "organizationId") REFERENCES "users" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "interviews" ADD CONSTRAINT "interviews_targetJobId_org_fk" FOREIGN KEY ("targetJobId", "organizationId") REFERENCES "target_jobs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "session_costs" ADD CONSTRAINT "session_costs_interviewId_org_fk" FOREIGN KEY ("interviewId", "organizationId") REFERENCES "interviews" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "usage_ledger" ADD CONSTRAINT "usage_ledger_userId_org_fk" FOREIGN KEY ("userId", "organizationId") REFERENCES "users" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "usage_ledger" ADD CONSTRAINT "usage_ledger_interviewId_org_fk" FOREIGN KEY ("interviewId", "organizationId") REFERENCES "interviews" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "messages" ADD CONSTRAINT "messages_interviewId_org_fk" FOREIGN KEY ("interviewId", "organizationId") REFERENCES "interviews" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "messages" ADD CONSTRAINT "messages_replyToMessageId_org_fk" FOREIGN KEY ("replyToMessageId", "organizationId") REFERENCES "messages" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "reports" ADD CONSTRAINT "reports_interviewId_org_fk" FOREIGN KEY ("interviewId", "organizationId") REFERENCES "interviews" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "reports" ADD CONSTRAINT "reports_currentEvaluationRunId_org_fk" FOREIGN KEY ("currentEvaluationRunId", "organizationId") REFERENCES "evaluation_runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "interview_tasks" ADD CONSTRAINT "interview_tasks_interviewId_org_fk" FOREIGN KEY ("interviewId", "organizationId") REFERENCES "interviews" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "answer_histories" ADD CONSTRAINT "answer_histories_interviewId_org_fk" FOREIGN KEY ("interviewId", "organizationId") REFERENCES "interviews" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "answer_histories" ADD CONSTRAINT "answer_histories_questionId_org_fk" FOREIGN KEY ("questionId", "organizationId") REFERENCES "interview_questions" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "answer_histories" ADD CONSTRAINT "answer_histories_answerId_org_fk" FOREIGN KEY ("answerId", "organizationId") REFERENCES "interview_answers" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "target_jobs" ADD CONSTRAINT "target_jobs_userId_org_fk" FOREIGN KEY ("userId", "organizationId") REFERENCES "users" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "job_skill_requirements" ADD CONSTRAINT "job_skill_requirements_targetJobId_org_fk" FOREIGN KEY ("targetJobId", "organizationId") REFERENCES "target_jobs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "interview_questions" ADD CONSTRAINT "interview_questions_interviewId_org_fk" FOREIGN KEY ("interviewId", "organizationId") REFERENCES "interviews" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "interview_questions" ADD CONSTRAINT "interview_questions_sourceTaskId_org_fk" FOREIGN KEY ("sourceTaskId", "organizationId") REFERENCES "interview_tasks" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "interview_questions" ADD CONSTRAINT "interview_questions_parentQuestionId_org_fk" FOREIGN KEY ("parentQuestionId", "organizationId") REFERENCES "interview_questions" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "interview_answers" ADD CONSTRAINT "interview_answers_interviewId_org_fk" FOREIGN KEY ("interviewId", "organizationId") REFERENCES "interviews" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "interview_answers" ADD CONSTRAINT "interview_answers_questionId_org_fk" FOREIGN KEY ("questionId", "organizationId") REFERENCES "interview_questions" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "interview_answers" ADD CONSTRAINT "interview_answers_messageId_org_fk" FOREIGN KEY ("messageId", "organizationId") REFERENCES "messages" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "evaluation_runs" ADD CONSTRAINT "evaluation_runs_interviewId_org_fk" FOREIGN KEY ("interviewId", "organizationId") REFERENCES "interviews" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "evaluation_runs" ADD CONSTRAINT "evaluation_runs_supersedesId_org_fk" FOREIGN KEY ("supersedesId", "organizationId") REFERENCES "evaluation_runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "assessment_evidence" ADD CONSTRAINT "assessment_evidence_evaluationRunId_org_fk" FOREIGN KEY ("evaluationRunId", "organizationId") REFERENCES "evaluation_runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "assessment_evidence" ADD CONSTRAINT "assessment_evidence_interviewId_org_fk" FOREIGN KEY ("interviewId", "organizationId") REFERENCES "interviews" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "assessment_evidence" ADD CONSTRAINT "assessment_evidence_questionId_org_fk" FOREIGN KEY ("questionId", "organizationId") REFERENCES "interview_questions" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "assessment_evidence" ADD CONSTRAINT "assessment_evidence_answerId_org_fk" FOREIGN KEY ("answerId", "organizationId") REFERENCES "interview_answers" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "candidate_skill_states" ADD CONSTRAINT "candidate_skill_states_userId_org_fk" FOREIGN KEY ("userId", "organizationId") REFERENCES "users" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "candidate_skill_states" ADD CONSTRAINT "candidate_skill_states_targetJobId_org_fk" FOREIGN KEY ("targetJobId", "organizationId") REFERENCES "target_jobs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "candidate_skill_states" ADD CONSTRAINT "candidate_skill_states_sourceRunId_org_fk" FOREIGN KEY ("sourceRunId", "organizationId") REFERENCES "evaluation_runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "training_recommendations" ADD CONSTRAINT "training_recommendations_userId_org_fk" FOREIGN KEY ("userId", "organizationId") REFERENCES "users" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "training_recommendations" ADD CONSTRAINT "training_recommendations_targetJobId_org_fk" FOREIGN KEY ("targetJobId", "organizationId") REFERENCES "target_jobs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "training_recommendations" ADD CONSTRAINT "training_recommendations_sourceRunId_org_fk" FOREIGN KEY ("sourceRunId", "organizationId") REFERENCES "evaluation_runs" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "training_recommendations" ADD CONSTRAINT "training_recommendations_sourceEvidenceId_org_fk" FOREIGN KEY ("sourceEvidenceId", "organizationId") REFERENCES "assessment_evidence" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "training_attempts" ADD CONSTRAINT "training_attempts_recommendationId_org_fk" FOREIGN KEY ("recommendationId", "organizationId") REFERENCES "training_recommendations" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "training_attempts" ADD CONSTRAINT "training_attempts_userId_org_fk" FOREIGN KEY ("userId", "organizationId") REFERENCES "users" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "training_attempts" ADD CONSTRAINT "training_attempts_retestInterviewId_org_fk" FOREIGN KEY ("retestInterviewId", "organizationId") REFERENCES "interviews" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "reflection_logs" ADD CONSTRAINT "reflection_logs_interviewId_org_fk" FOREIGN KEY ("interviewId", "organizationId") REFERENCES "interviews" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "reflection_logs" ADD CONSTRAINT "reflection_logs_userId_org_fk" FOREIGN KEY ("userId", "organizationId") REFERENCES "users" ("id", "organizationId") DEFERRABLE INITIALLY DEFERRED;
COMMIT;
-- 回滚：必须先停写并备份；多组织写入后禁止直接回退旧 API。恢复迁移前快照为首选。
-- 仅在确认无新增组织数据的测试库，可按以下 SQL 移除本迁移新增对象：
-- ALTER TABLE "reflection_logs" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "training_attempts" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "training_recommendations" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "candidate_skill_states" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "assessment_evidence" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "evaluation_runs" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "interview_answers" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "interview_questions" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "job_skill_requirements" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "target_jobs" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "answer_histories" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "interview_tasks" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "user_tool_preferences" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "reports" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "messages" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "usage_ledger" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "session_costs" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "interviews" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "evaluation_results" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "agent_evaluation_runs" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "evaluators" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "evaluation_dataset_cases" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "evaluation_datasets" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "tool_approvals" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "application_runs" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "applications" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "decision_evidence" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "fact_assertions" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "decision_records" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "trace_events" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "runs" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "agent_versions" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "agents" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "workspace_members" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "workspaces" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "lab_operation_logs" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "lab_release_decisions" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "lab_experiment_runs" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "lab_experiments" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "lab_failures" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "lab_recorded_imports" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "lab_runs" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "lab_agent_versions" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "lab_datasets" DROP COLUMN "organizationId" CASCADE;
-- ALTER TABLE "users" DROP COLUMN "organizationId" CASCADE;
-- DROP TABLE "organizations";
